MvcApplication1/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class BannerController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MvcApplication1/Controllers/HomeController.cs
using MvcApplication1.Business;
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace MvcApplication1.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            // Lấy danh sách các địa điểm nhà hàng
            var locationBL = new LocationBAL();
            var culinaryBL = new CulinaryBAL();
            ViewBag.AllCulinary = culinaryBL.GetAll();
            var lstLocation = locationBL.GetList();
            return View(lstLocation);
        }
        [AllowAnonymous]
        public ActionResult IsAuthenticated()
        {
            
            if (WebSecurity.IsAuthenticated)
            {
                var userInfo = new SignnedInUserModel();
                userInfo.UserName = WebSecurity.CurrentUserName;
                userInfo.IsLoggedIn = WebSecurity.IsAuthenticated;
                var userInformationBL = new UserInformationBAL();
                var currUserInfo = userInformationBL.GetByUserName(userInfo.UserName);
                if (currUserInfo != null)
                {
                    userInfo.UserEmail = currUserInfo.UserEmail;
                    userInfo.FirstName = currUserInfo.FirstName;
                    userInfo.LastName = currUserInfo.LastName;
                }
                return PartialView("_AuthenticatedPartial",userInfo );
            }
            else
            {
                return PartialView("_AnonymousPartial");
            }
        }
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        
    }
}

MvcApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

MvcApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

MvcApplication1/Views/Home/Index.cshtml
@using SeafoodEntity
@model List<Location>
@{
    var lstCulinary = (List<Culinary>)ViewBag.AllCulinary;
}

@section banner {
    @Html.Action("Index","Banner")
}

<div class="main-content-left">
    @Html.Partial("~/Views/Shared/_LeftContent_MainPagePartial.cshtml")
</div>
<div class="main-content-right">
    <div class="tool-right-content">
        <ul>
            <li><a href="javascript:void(0)" class="current">Mới nhất</a></li>
            <li><a href="javascript:void(0)">Gần tôi</a></li>
            <li></li>
            <li><a href="javascript:void(0)">Đã lưu</a></li>
            <li style="float: right;" >
                <select id="slDistrictPlace">
                    <option value="">- Quận/Huyện -</option>
                    <option value="25">Hoan Kiem District</option>
                    <option value="28">Tay Ho District</option>
                    <option value="20">Ba Dinh District</option>
                    <option value="29">Thanh Xuan District</option>
                    <option value="24">Hai Ba Trung District</option>
                    <option value="22">Dong Da District</option>
                    <option value="21">Cau Giay District</option>
                    <option value="26">Hoang Mai District</option>
                    <option value="27">Long Bien District</option>
                    <option value="23">Ha Dong District</option>
                    <option value="945">South Tu Liem District</option>
                    <option value="690">Bac Tu Liem District</option>
                    <option value="674">Ba Vi</option>
                    <option value="675">Chuong My</option>
                    <option value="676">Dan Phuong</option>
                    <option value="677">Dong Anh</option>
                    <option value="678">Gia Lam</option>
                    <option value="679">Hoai Duc</option>
                    <option value="680">Me Linh</option>
                    <option value="681">My Duc</option>
                    <option value="682">Phu Xuyen</option>
                    <option value="683">Phu Tho</option>
                    <option value="684">Quoc Oai</option>
                    <option value="685">Soc Son</option>
                    <option value="686">Thach That</option>
                    <option value="687">Thanh Oai</option>
                    <option value="688">Thanh Tri</option>
                    <option value="689">Thuong Tin</option>
                    <option value="691">Ung Hoa</option>
                    <option value="692">Son Tay</option>
                </select>
            </li>
            <li style="float: right;">
                <select class="ng-pristine ng-untouched ng-valid ng-empty">
                        <option value="">- Ẩm thực -</option>
                        @foreach (var culinaryItem in lstCulinary)
                        {
                            <option value="@culinaryItem.Id"> @culinaryItem.Name</option> 
                        }
                </select>
            </li>
            <li style="float: right;">
                <select class="ng-pristine ng-untouched ng-valid ng-empty">
                    <option value="">- Danh mục -</option>
                        <option value="12">Sang trọng</option>
                        <option value="39">Buffet</option>
                        <option value="1">Nhà hàng</option>
                        <option value="11">Ăn vặt/vỉa hè</option>
                        <option value="56">Ăn chay</option>
                        <option value="2">Café/Dessert</option>
                        <option value="3">Quán ăn</option>
                        <option value="4">Bar/Pub</option>
                        <option value="54">Quán nhậu</option>
                        <option value="43">Beer club</option>
                        <option value="6">Tiệm bánh</option>
                        <option value="44">Tiệc tận nơi</option>
                        <option value="27">Shop Online</option>
                        <option value="28">Giao cơm văn phòng</option>
                        <option value="79">Khu Ẩm Thực</option>
                </select>
            </li>
        </ul>
    </div>
    <div class="writer-content">
        @foreach (var item in Model)
        {
            <div class="content-item">
                <div class="avatar">
                    <a href="@item.HrefLink" target="_blank">
                        <img src="@item.RepImgLink">
                    </a>
                </div>
                <div class="items-content">
                    <div class="review-points">
                        <span class="ng-binding">5.0</span>
                    </div>
                    <div class="title fd-text-ellip">
                        <a href="@item.HrefLink" target="_blank"  class="ng-binding">@item.LocationName</a>
                    </div>
                    <div class="desc fd-text-ellip" >@item.Address</div>
                </div>
                <div class="items-review" >
                    <div class="avatar">
                        <a href="/thanh-vien/Tuyenoc">
                            <img src="https://media.foody.vn/default/s100/user-default-female.png">
                        </a>
                    </div>
                    <div class="users-content">
                        <a target="_blank" href="/thanh-vien/Tuyenoc">
                            <b >Tuyến Ốc</b>
                        </a>
                        <a target="_blank" href="/ha-noi/an-vat-an-trach/binh-luan-1477804">Quán đã chuyển về ngõ 126 hào nam rồi các bạn nhé</a>
                    </div>
                </div>
                <div class="items-count">
                    <a><i class="fa fa-comment"></i> <span class="ng-binding">1</span></a>
                    <a><i class="fa fa-camera"></i> <span class="ng-binding">6</span></a>
                    <i class="fa fa-bookmark"></i> <span class="ng-binding">0</span>
                    <a href="javascript:void(0)" class="item-save tool-custom-list-add" data-id="252832">
                        <i class="fa fa-bookmark"></i>
                        <span>Lưu</span>
                    </a>
                </div>
            </div>
        }
    </div>
</div>

MvcApplication1/Views/Home/_AnonymousPartial.cshtml
<div class="account-manager" ng-controller="MenuLoginController">
    <a class="fd-btn-login-new" ng-click="show_login_dialog()" ><span>Đăng nhập</span> </a>
</div>
<div id="NotificationCtrl" style="position:relative;float:left;">
    <div style="float:right;">
        <div class="notificationBox">
            <div class="notification-new-none">

            </div>
        </div>
    </div>
</div>
<div class="nav-add-buttons"  ng-controller ="AdditionalNavigationController"  click-anywhere-but-here="hide()" is-active="is_show" >
    <a ng-click="toggle_detail()" >+</a>
    <div id="add-buttons" ng-show="is_show" >
        <span class="arrow" style="left:257px;display:block;"></span>
        <ul>
            <li style="padding:8px 15px 6px 15px;border-bottom:#ddd 1px solid;" >Bạn có thể</li>
            <li>
                <a href="/them-dia-diem">
                    <span class="fa fa-map-marker icons" style="font-size:26px;"></span>
                    <span class="add-buttons-text">
                        <span class="text-main">Tạo địa điểm</span>
                        <br />
                        <span class="text-desc">Sẽ được duyệt trong vòng 48 tiếng</span>
                    </span>
                </a>
            </li>
            <li>
                <a class="add-new-reviews">
                    <span class="fa fa-comment icons"></span>
                    <span class="add-buttons-text">
                        <span class="text-main">Viết bình luận</span>
                        <br />
                        <span class="text-desc">Để chia sẻ trải nghiệm cho cộng đồng</span>
                    </span>
                </a>
            </li>
            <li>
                <a class="add-new-list">
                    <span class="fa fa-bars icons"></span>
                    <span class="add-buttons-text">
                        <span class="text-main">Tạo bộ sưu tập</span>
                        <br />
                        <span class="text-desc">Để lưu trữ địa điểm của bạn</span>
                    </span>
                </a>
            </li>
            <li>
                <a class="add-feedback">
                    <span class="fa fa-thumbs-down icons"></span>
                    <span class="add-buttons-text">
                        <span class="text-main">Góp ý</span>
                        <br />
                        <span class="text-desc">Để phục vụ bạn tốt hơn</span>
                    </span>
                </a>
            </li>
        </ul>
    </div>
</div>
<div class="language-dropdown-container">
    <a class="language-dropdown-btn">
        <img src="~/Content/img/vn.png" style="float:left;" />
    </a>
</div>

MvcApplication1/Views/Home/_AuthenticatedPartial.cshtml
@using MvcApplication1.Models
@model SignnedInUserModel

<div class="account-manager">
    <div id="account">
        <div class="topnav">
            <a href="javascript:void(0);" class="acemail">
                <div class="fname" title="Hazu">@Model.FirstName</div>
                <img src="https://media.foody.vn/usr/g899/8983480/avt/c30x30/foody-avatar-949-636352924754329699.jpg" class="avatar-user" alt="Hazu" title="Hazu">
            </a>
        </div>
        <div id="account_menu">
            <span class="arrow"></span>
            <div class="usermenudrop">
                <div class="useremail">
                    <div class="email">@Model.UserEmail</div>
                    <a href="javascript:void(0)" class="profile-verify-button">
                        <div class="toolbar-verify-full">
                            <div style="width:0%;"></div>
                        </div>
                        <div class="toolbar-verify-text">
                            <b>0%</b> xác thực
                        </div>
                    </a>
                </div>
                <div class="items">
                    <a href="/thanh-vien/manunghaycuoi#activity">
                        Hoạt Động Cá Nhân
                    </a>
                </div>
                <div class="items spector">
                    <a href="/thanh-vien/manunghaycuoi#archive-places/owner">
                        Lưu Trữ
                    </a>
                </div>
                <div class="items">
                    <a href="/thanh-vien/manunghaycuoi#history-delivery">
                        Lịch Sử Đặt Hàng 
                    </a>
                </div>
                <div class="items">
                    <a href="/thanh-vien/manunghaycuoi#paynow">
                        Thanh Toán PayNow
                    </a>
                </div>
                <div class="items spector">
                    <a href="/thanh-vien/manunghaycuoi#points">
                        Điểm Thưởng
                    </a>
                </div>
                <div class="items">
                    <a href="/thanh-vien/manunghaycuoi/dia-diem-da-tao">
                        Góp Ý
                    </a>
                </div>
                <div class="items">
                    <a href="/thanh-vien/manunghaycuoi/bo-suu-tap">
                        Cài Đặt Tài Khoản
                    </a>
                </div>
                <div class="items" style="border-top: #eee 1px solid;">
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id="FormLogOff"}))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:SignOut(0);" onclick="document.getElementById('FormLogOff').submit()" class="register">
                            Thoát<span class="fa fa-sign-out"></span>
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>