MvcApplication1/Controllers/CategoryController.cs
using MvcApplication1.Business;
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class CategoryController : Controller
    {
        [AllowAnonymous]
        [ChildActionOnly]
        public ActionResult GetAll()
        {
            var categoryGroupBAL = new CategoryGroupBAL();
            var lstCateGroup = categoryGroupBAL.GetAll();

            var categoryBAL = new CategoryBAL();
            var lstCategory = categoryBAL.GetAll();

            var model = new AllCategoryModel();
            model.LstCategory = lstCategory;
            model.LstCategoryGroup = lstCateGroup;
            return View(model);
        }
    }
}

MvcApplication1/Controllers/CityController.cs
using MvcApplication1.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace MvcApplication1.Controllers
{
    public class CityController : Controller
    {
        [AllowAnonymous]
        [ChildActionOnly]
        //[OutputCache(Duration = 86400)]
        public ActionResult GetAllCity()
        {
            var cityBAL = new CityBAL();
            var lstCity = cityBAL.GetAll();
            return View(lstCity);
        }
    }
}

MvcApplication1/Controllers/CommonController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class CommonController : Controller
    {

        public ActionResult Header()
        {
            return View();
        }
        [HttpGet]
        public virtual ActionResult Download(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] != null)
            {
                byte[] data = TempData[fileGuid] as byte[];
                if (TempData.ContainsKey(fileGuid))
                {
                    TempData.Remove(fileGuid);
                }
                return File(data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            }
            else
            {
                return new EmptyResult();
            }
        }

    }
}

MvcApplication1/Views/Shared/_Backend.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Phần mềm quản lý checkin sự kiện </title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/plugins/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
</head>
<body style="background-color: #E9E9EE;height:100%;">
    <div class="navbar navbar-inverse navbar-fixed-top menu-bar">
        @Html.Action("Header", "Common")
    </div>
    <div id="dialog-system">
    </div>
    <div class="container body-content" style=" margin:0 auto;width:1140px; background-color: #FFF;min-height:calc(100%);" id="main-content">
        @RenderBody()
    </div>
    <script src="~/Scripts/angular.min.js" type="text/javascript"></script>
    @RenderSection("Script", false)
</body>
</html>

MvcApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8"  />
        <title>Địa điểm ăn uống, ẩm thực, ăn gì ở đâu tại Hà Nội, nhà hàng, cafe | Ăn uống | Foody.vn</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <link href="~/Content/plugins/font-awesome-4.7.0/css/font-awesome.min.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/Main.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/fixed_layout.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/select_control.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/search_box.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/header_menu_select.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/header_app.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/banner.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/main_content.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/lastest_news.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/top_user_friend.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/footer_categoty_statistic.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/footer_admobile.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/footer_addtional_tool_and_company.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/register_container.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/account_manager.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/login_dialog.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/notification.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/navaddbuttons.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/add_location.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/my_profile_menu.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/my_profile.css" type="text/css" rel="stylesheet" />
        <link href="~/Content/location_detail.css" type="text/css" rel="stylesheet" />
    </head>
    <body ng-app="SeaFoodyApp" show-menubar-always-on-top >
        <div class="header">
            <div class="wraper-img banner-header-top">
                
                @Html.Partial("~/Views/Menu/_BannerHeaderTopPartial.cshtml")
            </div>
            <div class="header-menu">
                @Html.Partial("~/Views/Menu/_TopbarPartial.cshtml")
            </div>
            <div class="header-toolbar" id="header-toolbar">
                <div class="header-toolbar-wraper">
                    <a href="#" class="logo"> <img src="~/Content/img/foody-vn.png" alt="Foody.vn" /> </a>
                    @Html.Action("GetAllCity","City")
                    @Html.Action("GetAll", "Category")
                    @Html.Partial("~/Views/MainPageSearch/_SearchBarTopPartial.cshtml")
                    @Html.Partial("~/Views/Menu/_HeaderMenuSelect.cshtml")
                    <div class="header-apps">
                        <a href="/ung-dung-mobile" target="_blank"><span class="fa fa-mobile"></span>&nbsp;Apps</a>
                    </div>
                    <div class="longin-box-and-language" style="float:right;font-size:14px;">
                        @Html.Action("IsAuthenticated", "Home")
                    </div>
                </div>
            </div>
        </div>
        @RenderSection("banner",false)
        
        <div id="body" class="main-content">
            @RenderBody()
        </div>
        @Html.Partial("~/Views/UserInformation/_TopUser.cshtml")
        @Html.Partial("~/Views/Category/_Statistic.cshtml")
        @Html.Partial("~/Views/Footer/_AdMobile.cshtml")
        @Html.Partial("~/Views/Footer/_AdditionalToolAndCompany.cshtml")
        @*@Html.Action("ShowLoginDialog", "Account")*@
        <script src="~/Scripts/angular.min.js" type="text/javascript"></script>
        @Scripts.Render("~/Scripts/main-content.js")
        @*<script src="~/Scripts/angular.min.js" type="text/javascript"></script>
        <script src="~/Scripts/MainModule.js" type="text/javascript"></script>
        <script src="~/Scripts/Directives/ClickAnyWhereButHere.js" type="text/javascript"></script>
        <script src="~/Scripts/Directives/ShowMenuBarAlwaysOnTop.js" type="text/javascript"></script>
        <script src="~/Scripts/Services/DialogLoginService.js" type="text/javascript"></script>
        <script src="~/Scripts/CityController.js" type="text/javascript"></script>
        <script src="~/Scripts/CategoryController.js" type="text/javascript"></script>
        <script src="~/Scripts/LoginDialogController.js" type="text/javascript"></script>
        <script src="~/Scripts/MenuLoginController.js" type="text/javascript"></script>
        <script src="~/Scripts/AdditionalNavigationController.js" type="text/javascript"></script>
        <script src="~/Scripts/LocationForCreateController.js" type="text/javascript"></script>
        <script src="~/Scripts/UserInformationController.js" type="text/javascript"></script>*@
        @RenderSection("scripts", required: false)
    </body>
</html>

MvcApplication1/Views/Shared/_LeftContent_MainPagePartial.cshtml
<div class="category">
    Danh mục
</div>
<ul>
    <li>
        <a href="#places" class="active">Ở đâu <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#booking">Đặt bàn <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#delivery">Giao hàng <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#foods">Ăn gì <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#collections">Sưu tập <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#video">TV <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#reviews">Bình luận <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#food/articles">Blogs <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#promotion">Khuyến mãi <i class="fa fa-angle-right"></i></a>
    </li>
    <li>
        <a href="#bank-card">Bank-Card <i class="fa fa-angle-right"></i></a>
        @*ng-class="{'active':MenuId=='10'}" *@
    </li>
</ul>

MvcApplication1/Views/Shared/_SSOLayout.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="SSOApp" >
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div>
            @RenderBody()
        </div>
        <script src="~/Scripts/angular.min.js" type="text/javascript"></script>
        @Scripts.Render("~/bundles/main-content");
        @RenderSection("scripts", required: false)
    </body>
</html>