SeafoodAdmin/Controllers/LocationController.cs
using HelperLib;
using SeafoodAdmin.Business;
using SeafoodAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SeafoodAdmin.Controllers
{
    [Authorize]
    public class LocationController:Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search(LocationForSearchModel model)
        {
            var locationBL = new LocationBL();
            return View(locationBL.GetList(model));
        }

        public JsonResult Approve(int id)
        {
            var response = new ResponseModel();
            var locationBL = new LocationBL();
            locationBL.Appove(id);
            response.Code = SystemStatusCode.Success.GetHashCode();
            response.Message = "Bạn đã duyệt thông tin địa điểm thành công !";
            return Json(response, JsonRequestBehavior.AllowGet);
        }

    }
}

SeafoodAdmin/Views/Location/Index.cshtml
@{
}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h3 class="page-title">Danh sách địa điểm chưa được duyệt <small>Hiển thị danh sách các địa điểm chưa được duyệt bởi người quản trị website</small> </h3>
            <ul class="breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="/Home/Index">Trang chủ</a>
                    <i class="icon-angle-right"></i>
                </li>
                <li>
                    <a href="/Location/Index">Danh sách các địa điểm chưa được duyệt</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption"><i class="icon-reorder"></i>Tiêu chí tìm kiếm</div>
                    <div class="actions">
                        @*<a href="#" class="btn yellow"><i class="icon-pencil"></i> Edit</a>
                            <a href="#" class="btn green"><i class="icon-plus"></i> Add</a>*@
                    </div>
                </div>
                <div class="portlet-body">
                    <button type="button" class="btn green" id="btnSearch">
                        <i class="icon-search"></i>
                        Tìm kiếm
                    </button>
                </div>
            </div>
        </div>
    </div>
    @Html.Action("Search", "Location")
</div>
@section Script
{
    <script type="text/javascript" src="~/Content/assets/scripts/views/location.js"></script>
    <script type="text/javascript">
        location_index.init();
    </script>
}

SeafoodAdmin/Views/Location/Search.cshtml
@using SeafoodEntity;
@model List<Location>
@{
    Layout = null;
    var count = 1;
}
<div class="row-fluid">
    <div class="span12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption"><i class="icon-reorder"></i>Danh sách địa điểm</div>
                <div class="actions">
                    @*<a href="#" class="btn yellow"><i class="icon-pencil"></i> Edit</a>
                    <a href="#" class="btn green"><i class="icon-plus"></i> Add</a>*@
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-condensed table-hover" id="table-unappove-location" >
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tên địa điểm</th>
                            <th>Địa chỉ</th>
                            <th>Trạng thái</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var locationItem in Model)
                        {
                            <tr>
                                <td>@(count++)</td>
                                <td>@(locationItem.LocationName)</td>
                                <td>@(locationItem.Address)</td>
                                <td>
                                    @if(locationItem.IsApproved)
                                    {
                                        <span class="label label-success">Đã duyệt</span>
                                    }
                                    else
                                    {
                                        <span class="label label-default">Chưa duyệt</span>
                                    }
                                </td>
                                <td>
                                    @if(!locationItem.IsApproved)
                                    {
                                        <div class="btn-group">
                                          <a class="btn mini blue" href="#" data-toggle="dropdown">
                                              <i class="icon-cog"></i> Quản lý
                                              <i class="icon-angle-down"></i>
                                          </a>
                                          <ul class="dropdown-menu">
                                             <li><a href="javascript:void(0);" name="approve" data-location-id="@(locationItem.LocationId)"><i class="icon-ok"></i> Duyệt</a></li>
                                          </ul>
                                       </div>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>